# Generated by Django 2.2.5 on 2019-09-07 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190906_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 9, 7, 3, 53, 14, 858146, tzinfo=utc)),
        ),
    ]
